### PR TITLE
Lab 2

### PR DESCRIPTION
**Pull request by Osipchik**

### CODE REVIEW

**Review by gmltA — COMMENTED** [review]
I don't get it. Did you just took the markup from the spotify website or what?

**Comment by Osipchik** [comment]
No, I only took the design. The markup is pretty easy that is why it does not have the sense to take it from the real site. The website has a couple of components that use on the most of pages. And these components are interactive so I have no choice but to use a lot of `<div>` tag, because it is not good practice to wrap interactive elements with `<a>` tag. And as an example of markup, I used the project I work with at work.

Also, they use two web apps, one for desktop and one for mobile but I need to do this in one app.

And, I'm want to implement a different logic on this site and want to create a web version for a mobile device that looks like a mobile app because the web version of Spotify for a mobile device is not so good as the mobile app.

**Review by gmltA — COMMENTED** [review]
Okay. That's a <kbd>8</kbd>. Is that enough?

**Comment by Osipchik** [comment]
Yeah, ok.

**Review by gmltA — APPROVED** [review]

**Pull request merged**
