### PR TITLE
Lab 3

### PR DESCRIPTION
**Pull request by Osipchik**
[deploy link](https://osipchik.github.io/FrontEnd_tasks/index.html)

tiles on the search page will be colored for it I will use js and header will have background color on scroll, I also will use js for it

### CODE REVIEW

**Review by gmltA — CHANGES_REQUESTED** [review]
Okay you clearly stole some styles from the original website. I can give you <kbd>9</kbd> if you'll be able to add a new page for new track upload. There should be a bunch of inputs to enter song metadata and a file-picker.

**Comment by Osipchik** [comment]
cool, I already have the page for this think soon I will send new pr with new lab

**Comment by gmltA** [comment]
But you didn't push anything since the last review?

**Comment by Osipchik** [comment]
yes, I didn’t add anything to this pr. 
I've added many input fields in [this pr](https://github.com/Osipchik/FrontEnd_tasks/pull/4). 

I think it can be closed even if the score is below 9

**Comment by gmltA** [comment]
I don't understand. I need to see requested changes here, in this PR.

**Comment by Osipchik** [comment]
pages with inputs:
[add/change track](https://osipchik.github.io/FrontEnd_tasks/upload-file.html)
[add/change album](https://osipchik.github.io/FrontEnd_tasks/create-album.html)

change-profile is the same as change album but without description

**Review by gmltA — APPROVED** [review]
Good. That's a <kbd>9</kbd>.

**Pull request closed without merging**
